# Service Configuration
service:
  type: ClusterIP
  port: 80

# Image Configuration
image:
  repository: muhammedrashid/helm  # Replace with your actual Docker Hub repository
  tag: latest
  pullPolicy: Always

# Deployment Configuration
replicaCount: 2  # Set the number of replicas

# Resource Requests & Limits
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

# Ingress Configuration (Disabled)
ingress:
  enabled: false  # Set to true if you need ingress later
  annotations: {}
  hosts: []
  tls: []

# Service Account (Optional)
serviceAccount:
  create: true
  name: ""

# Liveness and Readiness Probes
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

# Autoscaling (Disabled by default)
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
